### ISSUE TITLE
Should "runtime" be "runtimeClasspath" for Gradle 7 compatibility?

### ISSUE THREAD

**Issue by paulk-asert** [blindpirate/gradle-legacy-osgi-plugin#3]
https://github.com/blindpirate/gradle-legacy-osgi-plugin/blob/4e0674e03dfabe7dc1b8ee9cd96d0531c968675c/src/main/java/com/github/blindpirate/osgi/plugins/osgi/OsgiPlugin.java#L60

**Comment by blindpirate** [comment]
Yes, fixing.

**Comment by paulk-asert** [comment]
I'll close since this was fixed in 0.0.6. Thanks.
